# Netlify configuration file

# Build settings
[build]
  publish = "dist"
  command = "npm run build"

# Redirects and rewrites
[[redirects]]
  # Redirect all paths to index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  # Define headers for all files
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for locales
[[headers]]
  for = "/locales/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"