
name: Daily Blog Post

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate new blog post
      env:
        API_KEY: ${{ secrets.YOUR_API_KEY }} # Add your API key to GitHub secrets
        API_ENDPOINT: ${{ secrets.YOUR_API_ENDPOINT }}
      run: python scripts/generate_blog_post.py

    - name: Commit new blog posts
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add content/*
        git commit -m "feat: Add daily blog post"
        git push

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Node.js dependencies
      run: npm install

    - name: Build website
      run: npm run build

    - name: Deploy to GitHub Pages
      run: ./deploy-gh-pages.sh
